version: '3'

tasks:
  build:
    cmds:
      - docker build --platform linux/amd64 -t {{.REPO}}:{{.TAG}} {{.PROJECT}}

  push:
    cmds:
      - docker push {{.REPO}}:{{.TAG}}

  airflow:
    vars:
      REPO: harbor.ingtra.net/library/airflow
      TAG: 2.3.3
      PROJECT: airflow
    cmds:
      - task: build
        vars:
          REPO: "{{.REPO}}"
          TAG: "{{.TAG}}"
          PROJECT: "{{.PROJECT}}"
      - task: push
        vars:
          REPO: "{{.REPO}}"
          TAG: "{{.TAG}}"

  querybook:
    vars:
      REPO: harbor.ingtra.net/library/querybook
      TAG: 3.4.0
      PROJECT: querybook
    cmds:
      - task: build
        vars:
          REPO: "{{.REPO}}"
          TAG: "{{.TAG}}"
          PROJECT: "{{.PROJECT}}"
      - task: push
        vars:
          REPO: "{{.REPO}}"
          TAG: "{{.TAG}}"

  spark:
    vars:
      REPO: harbor.ingtra.net/library/spark
      TAG: 3.3.0
      PROJECT: spark
    cmds:
      - task: build
        vars:
          REPO: "{{.REPO}}" 
          TAG: "{{.TAG}}"
          PROJECT: "{{.PROJECT}}"
      - task: push
        vars:
          REPO: "{{.REPO}}"
          TAG: "{{.TAG}}"
  
  kyuubi:
    vars:
      REPO: harbor.ingtra.net/library/kyuubi
      TAG: 3.3.0
      SPARK_IMAGE: harbor.ingtra.net/library/spark:3.3.0
      VERSION: 1.5.2
      TEMP_DIR:
        sh: mktemp -d
    env:
      ARCHS: --platform linux/amd64
    dir: "{{.TEMP_DIR}}"
    cmds:
      - wget https://dlcdn.apache.org/incubator/kyuubi/kyuubi-{{.VERSION}}-incubating/apache-kyuubi-{{.VERSION}}-incubating-bin.tgz
      - tar zxvf apache-kyuubi-{{.VERSION}}-incubating-bin.tgz
      - |
        ./apache-kyuubi-{{.VERSION}}-incubating-bin//bin/docker-image-tool.sh \
          -r {{.REPO}} -t {{.TAG}} -S /opt/spark -b BASE_IMAGE={{.SPARK_IMAGE}} build
      - docker push {{.REPO}}:{{.TAG}}
