version: '3'

tasks:
  airflow:
    vars:
      REPO: harbor.ingtra.net/library/airflow
      TAG: 2.3.3
    cmds:
      - docker build --platform linux/amd64 -t {{.REPO}}:{{.TAG}} airflow
      - docker push {{.REPO}}:{{.TAG}}

  querybook:
    vars:
      REPO: harbor.ingtra.net/library/querybook
      TAG: 3.4.0
      PROJECT: querybook
    cmds:
      - docker build --platform linux/amd64 -t {{.REPO}}:{{.TAG}} querybook
      - docker push {{.REPO}}:{{.TAG}}

  spark-base:
    vars:
      REPO: harbor.ingtra.net/library/spark
      TAG: "{{.SPARK_VERSION}}-scala{{.SCALA_VERSION}}-java{{.JAVA_VERSION}}-iceberg{{.ICEBERG_VERSION}}"
    cmds:
      - |
        docker build --platform linux/amd64 -t {{.REPO}}:{{.TAG}} \
          --build-arg SPARK_VERSION={{.SPARK_VERSION}} \
          --build-arg JAVA_VERSION={{.JAVA_VERSION}} \
          --build-arg SCALA_VERSION={{.SCALA_VERSION}} \
          --build-arg ICEBERG_VERSION={{.ICEBERG_VERSION}} \
          spark
      - docker push {{.REPO}}:{{.TAG}}

  spark:
    cmds:
      - task: spark-base
        vars:
          SPARK_VERSION: 3.3.0
          SCALA_VERSION: 2.13
          JAVA_VERSION: 17
          ICEBERG_VERSION: 0.14.0
      - task: spark-base
        vars:
          SPARK_VERSION: 3.3.0
          SCALA_VERSION: 2.13
          JAVA_VERSION: 11
          ICEBERG_VERSION: 0.14.0
      - task: spark-base
        vars:
          SPARK_VERSION: 3.3.0
          SCALA_VERSION: 2.12
          JAVA_VERSION: 11
          ICEBERG_VERSION: 0.14.0

  
  kyuubi:
    vars:
      REPO: harbor.ingtra.net/library
      TAG: 1.5.2
      SPARK_IMAGE: harbor.ingtra.net/library/spark:3.3.0-scala2.13-java11-iceberg0.14.0
      VERSION: 1.5.2
      TEMP_DIR:
        sh: mktemp -d
    env:
      ARCHS: --platform linux/amd64
    dir: "{{.TEMP_DIR}}"
    cmds:
      - wget https://dlcdn.apache.org/incubator/kyuubi/kyuubi-{{.VERSION}}-incubating/apache-kyuubi-{{.VERSION}}-incubating-bin.tgz
      - tar zxvf apache-kyuubi-{{.VERSION}}-incubating-bin.tgz
      - |
        ./apache-kyuubi-{{.VERSION}}-incubating-bin//bin/docker-image-tool.sh \
          -r {{.REPO}} -t {{.TAG}} -S /opt/spark -b BASE_IMAGE={{.SPARK_IMAGE}} build
      - docker push {{.REPO}}/kyuubi:{{.TAG}}
