ARG IMAGE_VERSION
FROM nvcr.io/nvidia/l4t-base:$IMAGE_VERSION
ARG K0S_VERSION

RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_$(uname -m) && \
    chmod +x /usr/local/bin/dumb-init
RUN apt-get update -y && apt-get install -y nvidia-container-runtime iproute2 iptables && apt-get clean
RUN curl -sSLf https://get.k0s.sh | K0S_VERSION=$K0S_VERSION sh

COPY entrypoint.sh /
ENTRYPOINT ["/usr/local/bin/dumb-init", "--", "/entrypoint.sh"]