ARG IMAGE_VERSION
FROM rockylinux:$IMAGE_VERSION
ARG K0S_VERSION

RUN dnf install -y wget
RUN wget -O /usr/local/bin/dumb-init https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_$(uname -m) && \
    chmod +x /usr/local/bin/dumb-init
RUN curl -sSLf https://get.k0s.sh | K0S_VERSION=$K0S_VERSION sh

COPY entrypoint.sh /
ENTRYPOINT ["/usr/local/bin/dumb-init", "--", "/entrypoint.sh"]