name: Build Images
run-name: ${{ github.repository }} is building container images
on:
  - push
  - workflow_dispatch
jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.0
        with:
          paths_filter: |
            airflow:
              paths: ["airflow/**"]
            querybook:
              paths: ["querybook/**"]
            spark:
              paths: ["spark/**"]
          do_not_skip: '["workflow_dispatch"]'
  build_airflow:
    needs: skip_check
    if: "!fromJSON(needs.skip_check.outputs.paths_result).airflow.should_skip"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        airflow_version: 
          - 2.4.3
        python_version:
          - 3.11
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ingtranet/airflow:latest
          build-args: |
            AIRFLOW_VERSION=${{ matrix.airflow_version }}
            PYTHON_VERSION=${{ matrix.python_version }}
          context: airflow

